// Seti file icons (https://github.com/jesseweed/seti-ui). Each SVG carries its
// Seti colour. We eagerly import the whole set as URLs and map file
// names/extensions onto the appropriate icon, falling back to `default`.
//
// The associations below are ported verbatim from VS Code's bundled Seti theme
// (`extensions/theme-seti/icons/vs-seti-icon-theme.json`) so the file tree shows
// exactly the same icon VS Code does. VS Code resolves an icon in this order:
//   1. exact file name (`BY_FILENAME`)
//   2. longest matching extension suffix (`BY_EXT`)
//   3. the file's language association by last extension (`BY_LANG`)

// `sync` (not `eager`) so each module resolves to the URL synchronously — `eager`
// returns a Promise per module.
const ctx = import.meta.webpackContext('../icons', {
  regExp: /\.svg$/,
  mode: 'sync',
});

/** @type {Record<string, string>} icon name → asset URL */
const ICONS = {};
for (const key of ctx.keys()) {
  const name = key.replace(/^\.\//, '').replace(/\.svg$/, '');
  const mod = ctx(key);
  ICONS[name] = mod.default ?? mod;
}

// Exact file names (case-insensitive) → icon. From the Seti theme's `fileNames`.
const BY_FILENAME = {
  mix: 'hex',
  'karma.conf.js': 'karma',
  'karma.conf.cjs': 'karma',
  'karma.conf.mjs': 'karma',
  'karma.conf.coffee': 'karma',
  'readme.md': 'info',
  'readme.txt': 'info',
  readme: 'info',
  'changelog.md': 'clock',
  'changelog.txt': 'clock',
  changelog: 'clock',
  'changes.md': 'clock',
  'changes.txt': 'clock',
  changes: 'clock',
  'version.md': 'clock',
  'version.txt': 'clock',
  version: 'clock',
  mvnw: 'maven',
  'pom.xml': 'maven',
  'tsconfig.json': 'tsconfig',
  'vite.config.js': 'vite',
  'vite.config.ts': 'vite',
  'vite.config.mjs': 'vite',
  'vite.config.mts': 'vite',
  'vite.config.cjs': 'vite',
  'vite.config.cts': 'vite',
  'swagger.json': 'json',
  'swagger.yml': 'json',
  'swagger.yaml': 'json',
  'mime.types': 'config',
  jenkinsfile: 'jenkins',
  'babel.config.js': 'babel',
  'babel.config.json': 'babel',
  'babel.config.cjs': 'babel',
  build: 'bazel',
  'build.bazel': 'bazel',
  workspace: 'bazel',
  'workspace.bazel': 'bazel',
  'bower.json': 'bower',
  'docker-healthcheck': 'docker',
  'eslint.config.js': 'eslint',
  geckodriver: 'firefox',
  'gruntfile.js': 'grunt',
  'gruntfile.babel.js': 'grunt',
  'gruntfile.coffee': 'grunt',
  gulpfile: 'gulp',
  'gulpfile.js': 'gulp',
  'ionic.config.json': 'ionic',
  'ionic.project': 'ionic',
  'platformio.ini': 'platformio',
  'rollup.config.js': 'rollup',
  'sass-lint.yml': 'sass',
  'stylelint.config.js': 'stylelint',
  'stylelint.config.cjs': 'stylelint',
  'stylelint.config.mjs': 'stylelint',
  'yarn.clean': 'yarn',
  'yarn.lock': 'yarn',
  'webpack.config.js': 'webpack',
  'webpack.config.cjs': 'webpack',
  'webpack.config.mjs': 'webpack',
  'webpack.config.ts': 'webpack',
  'webpack.config.build.js': 'webpack',
  'webpack.config.build.cjs': 'webpack',
  'webpack.config.build.mjs': 'webpack',
  'webpack.config.build.ts': 'webpack',
  'webpack.common.js': 'webpack',
  'webpack.common.cjs': 'webpack',
  'webpack.common.mjs': 'webpack',
  'webpack.common.ts': 'webpack',
  'webpack.dev.js': 'webpack',
  'webpack.dev.cjs': 'webpack',
  'webpack.dev.mjs': 'webpack',
  'webpack.dev.ts': 'webpack',
  'webpack.prod.js': 'webpack',
  'webpack.prod.cjs': 'webpack',
  'webpack.prod.mjs': 'webpack',
  'webpack.prod.ts': 'webpack',
  // Rspack & Rsbuild aren't in the upstream theme; they reuse the webpack icon
  // (as is conventional for the Rspack toolchain).
  'rspack.config.js': 'webpack',
  'rspack.config.cjs': 'webpack',
  'rspack.config.mjs': 'webpack',
  'rspack.config.ts': 'webpack',
  'rsbuild.config.js': 'webpack',
  'rsbuild.config.cjs': 'webpack',
  'rsbuild.config.mjs': 'webpack',
  'rsbuild.config.ts': 'webpack',
  license: 'license',
  licence: 'license',
  'license.txt': 'license',
  'licence.txt': 'license',
  'license.md': 'license',
  'licence.md': 'license',
  copying: 'license',
  'copying.txt': 'license',
  'copying.md': 'license',
  compiling: 'license',
  'compiling.txt': 'license',
  'compiling.md': 'license',
  contributing: 'license',
  'contributing.txt': 'license',
  'contributing.md': 'license',
  qmakefile: 'makefile',
  omakefile: 'makefile',
  'cmakelists.txt': 'makefile',
  procfile: 'heroku',
  todo: 'todo',
  'todo.txt': 'todo',
  'todo.md': 'todo',
  'npm-debug.log': 'npm_ignored',
  // Common config/dotfile names VS Code resolves via `fileNames`/language.
  '.gitignore': 'git_ignore',
  '.npmignore': 'npm_ignored',
  'package.json': 'npm',
  'package-lock.json': 'npm',
  'npm-shrinkwrap.json': 'npm',
  'firebase.json': 'firebase',
  dockerfile: 'docker',
  'docker-compose.yml': 'docker',
  'docker-compose.yaml': 'docker',
  makefile: 'makefile',
  gemfile: 'ruby',
  rakefile: 'ruby',
  'cargo.toml': 'rust',
  'go.mod': 'go2',
  'go.sum': 'go2',
};

// Extension suffix → icon, from the Seti theme's `fileExtensions`. The resolver
// tries the longest suffix first, so `foo.spec.ts` matches `spec.ts` before `ts`.
const BY_EXT = {
  bsl: 'bsl',
  mdo: 'mdo',
  cls: 'salesforce',
  apex: 'salesforce',
  asm: 'asm',
  s: 'asm',
  bicep: 'bicep',
  bzl: 'bazel',
  bazel: 'bazel',
  build: 'bazel',
  workspace: 'bazel',
  bazelignore: 'bazel',
  bazelversion: 'bazel',
  h: 'c',
  aspx: 'html',
  ascx: 'html',
  asax: 'html',
  master: 'html',
  hh: 'cpp',
  hpp: 'cpp',
  hxx: 'cpp',
  'h++': 'cpp',
  edn: 'clojure',
  cfc: 'coldfusion',
  cfm: 'coldfusion',
  litcoffee: 'coffee',
  config: 'config',
  cr: 'crystal',
  ecr: 'crystal_embedded',
  slang: 'crystal_embedded',
  cson: 'json',
  'css.map': 'css',
  sss: 'css',
  csv: 'csv',
  xls: 'xls',
  xlsx: 'xls',
  cuh: 'cu',
  hu: 'cu',
  cake: 'cake',
  ctp: 'cake_php',
  d: 'd',
  doc: 'word',
  docx: 'word',
  ejs: 'ejs',
  ex: 'elixir',
  exs: 'elixir_script',
  elm: 'elm',
  ico: 'favicon',
  gitconfig: 'git',
  gitkeep: 'git',
  gitattributes: 'git',
  gitmodules: 'git',
  slide: 'go',
  article: 'go',
  gd: 'godot',
  godot: 'godot',
  tres: 'godot',
  tscn: 'godot',
  gradle: 'gradle',
  gsp: 'grails',
  gql: 'graphql',
  graphql: 'graphql',
  graphqls: 'graphql',
  hack: 'hacklang',
  haml: 'haml',
  hs: 'haskell',
  lhs: 'haskell',
  hx: 'haxe',
  hxs: 'haxe',
  hxp: 'haxe',
  hxml: 'haxe',
  jade: 'jade',
  class: 'java',
  classpath: 'java',
  'js.map': 'javascript',
  'cjs.map': 'javascript',
  'mjs.map': 'javascript',
  'spec.js': 'javascript',
  'spec.cjs': 'javascript',
  'spec.mjs': 'javascript',
  'test.js': 'javascript',
  'test.cjs': 'javascript',
  'test.mjs': 'javascript',
  es: 'javascript',
  es5: 'javascript',
  es7: 'javascript',
  jinja: 'jinja',
  jinja2: 'jinja',
  kt: 'kotlin',
  kts: 'kotlin',
  liquid: 'liquid',
  ls: 'livescript',
  argdown: 'argdown',
  ad: 'argdown',
  mustache: 'mustache',
  stache: 'mustache',
  nim: 'nim',
  nims: 'nim',
  'github-issues': 'github',
  ipynb: 'notebook',
  njk: 'nunjucks',
  nunjucks: 'nunjucks',
  nunjs: 'nunjucks',
  nunj: 'nunjucks',
  njs: 'nunjucks',
  nj: 'nunjucks',
  'npm-debug.log': 'npm',
  npmignore: 'npm',
  npmrc: 'npm',
  ml: 'ocaml',
  mli: 'ocaml',
  cmx: 'ocaml',
  cmxa: 'ocaml',
  odata: 'odata',
  'php.inc': 'php',
  pipeline: 'pipeline',
  pddl: 'pddl',
  plan: 'plan',
  happenings: 'happenings',
  prisma: 'prisma',
  pp: 'puppet',
  epp: 'puppet',
  purs: 'purescript',
  'spec.jsx': 'react',
  'test.jsx': 'react',
  cjsx: 'react',
  'spec.tsx': 'react',
  'test.tsx': 'react',
  re: 'reasonml',
  res: 'rescript',
  resi: 'rescript',
  r: 'R',
  rmd: 'R',
  erb: 'html_erb',
  'erb.html': 'html_erb',
  'html.erb': 'html_erb',
  sass: 'sass',
  springbeans: 'spring',
  slim: 'slim',
  'smarty.tpl': 'smarty',
  tpl: 'smarty',
  sbt: 'sbt',
  scala: 'scala',
  sol: 'ethereum',
  styl: 'stylus',
  svelte: 'svelte',
  soql: 'db',
  tf: 'terraform',
  'tf.json': 'terraform',
  tfvars: 'terraform',
  'tfvars.json': 'terraform',
  dtx: 'tex',
  ins: 'tex',
  toml: 'config',
  twig: 'twig',
  'spec.ts': 'typescript',
  'test.ts': 'typescript',
  vala: 'vala',
  vapi: 'vala',
  component: 'html',
  vue: 'vue',
  wasm: 'wasm',
  wat: 'wat',
  pro: 'prolog',
  zig: 'zig',
  jar: 'zip',
  zip: 'zip',
  wgt: 'wgt',
  ai: 'illustrator',
  psd: 'photoshop',
  pdf: 'pdf',
  eot: 'font',
  ttf: 'font',
  woff: 'font',
  woff2: 'font',
  otf: 'font',
  avif: 'image',
  gif: 'image',
  jpg: 'image',
  jpeg: 'image',
  png: 'image',
  pxm: 'image',
  svg: 'svg',
  svgx: 'image',
  tiff: 'image',
  webp: 'image',
  'sublime-project': 'sublime',
  'sublime-workspace': 'sublime',
  mov: 'video',
  ogv: 'video',
  webm: 'video',
  avi: 'video',
  mpg: 'video',
  mp4: 'video',
  mp3: 'audio',
  ogg: 'audio',
  wav: 'audio',
  flac: 'audio',
  '3ds': 'svg',
  '3dm': 'svg',
  stl: 'svg',
  obj: 'svg',
  dae: 'svg',
  babelrc: 'babel',
  'babelrc.js': 'babel',
  'babelrc.cjs': 'babel',
  bazelrc: 'bazel',
  bowerrc: 'bower',
  dockerignore: 'docker',
  'codeclimate.yml': 'code-climate',
  eslintrc: 'eslint',
  'eslintrc.js': 'eslint',
  'eslintrc.cjs': 'eslint',
  'eslintrc.yaml': 'eslint',
  'eslintrc.yml': 'eslint',
  'eslintrc.json': 'eslint',
  eslintignore: 'eslint',
  firebaserc: 'firebase',
  'gitlab-ci.yml': 'gitlab',
  jshintrc: 'javascript',
  jscsrc: 'javascript',
  stylelintrc: 'stylelint',
  'stylelintrc.json': 'stylelint',
  'stylelintrc.yaml': 'stylelint',
  'stylelintrc.yml': 'stylelint',
  'stylelintrc.js': 'stylelint',
  stylelintignore: 'stylelint',
  direnv: 'config',
  static: 'config',
  slugignore: 'config',
  tmp: 'clock',
  htaccess: 'config',
  key: 'lock',
  cert: 'lock',
  cer: 'lock',
  crt: 'lock',
  pem: 'lock',
  ds_store: 'ignored',
};

// Last-extension → icon, from the Seti theme's `languageIds`. VS Code derives
// the icon from the file's language when no `fileExtensions` entry matches, so
// e.g. `.ts`/`.js`/`.md` (absent from `fileExtensions`) resolve here.
const BY_LANG = {
  // typescript / javascript
  ts: 'typescript',
  cts: 'typescript',
  mts: 'typescript',
  tsx: 'react',
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  es6: 'javascript',
  pac: 'javascript',
  jsx: 'react',
  // markup / data
  md: 'markdown',
  mkd: 'markdown',
  mdwn: 'markdown',
  mdown: 'markdown',
  markdown: 'markdown',
  markdn: 'markdown',
  mdtxt: 'markdown',
  mdtext: 'markdown',
  workbook: 'markdown',
  json: 'json',
  jsonc: 'json',
  jsonl: 'json',
  ndjson: 'json',
  har: 'json',
  webmanifest: 'json',
  yml: 'yml',
  yaml: 'yml',
  eyaml: 'yml',
  eyml: 'yml',
  cff: 'yml',
  html: 'html',
  htm: 'html',
  xhtml: 'html',
  shtml: 'html',
  xht: 'html',
  jshtm: 'html',
  volt: 'html',
  cshtml: 'html',
  razor: 'html',
  xml: 'xml',
  xsd: 'xml',
  xsl: 'xml',
  xslt: 'xml',
  xaml: 'xml',
  csproj: 'xml',
  vbproj: 'xml',
  vcxproj: 'xml',
  fsproj: 'xml',
  proj: 'xml',
  props: 'xml',
  targets: 'xml',
  plist: 'xml',
  storyboard: 'xml',
  xib: 'xml',
  resx: 'xml',
  rss: 'xml',
  atom: 'xml',
  wsdl: 'xml',
  // styles
  css: 'css',
  pcss: 'css',
  postcss: 'css',
  scss: 'sass',
  less: 'less',
  // c family
  c: 'c',
  i: 'c',
  m: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  'c++': 'cpp',
  ii: 'cpp',
  ino: 'cpp',
  inl: 'cpp',
  ipp: 'cpp',
  tpp: 'cpp',
  mm: 'cpp',
  cu: 'cu',
  cs: 'c-sharp',
  csx: 'c-sharp',
  fs: 'f-sharp',
  fsi: 'f-sharp',
  fsx: 'f-sharp',
  fsscript: 'f-sharp',
  // jvm
  java: 'java',
  jav: 'java',
  groovy: 'grails',
  gvy: 'grails',
  // go / rust / others
  go: 'go2',
  rs: 'rust',
  swift: 'swift',
  dart: 'dart',
  lua: 'lua',
  jl: 'julia',
  zig: 'zig',
  // scripting
  rb: 'ruby',
  rbx: 'ruby',
  rjs: 'ruby',
  gemspec: 'ruby',
  rake: 'ruby',
  ru: 'ruby',
  podspec: 'ruby',
  rbi: 'ruby',
  py: 'python',
  pyi: 'python',
  pyc: 'python',
  pyd: 'python',
  pyw: 'python',
  rpy: 'python',
  gyp: 'python',
  gypi: 'python',
  pl: 'perl',
  pm: 'perl',
  pod: 'perl',
  psgi: 'perl',
  php: 'php',
  php4: 'php',
  php5: 'php',
  phtml: 'php',
  blade: 'php',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  ksh: 'shell',
  csh: 'shell',
  ps1: 'powershell',
  psm1: 'powershell',
  psd1: 'powershell',
  pssc: 'powershell',
  psrc: 'powershell',
  bat: 'windows',
  cmd: 'windows',
  // databases / templating
  sql: 'db',
  dsql: 'db',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  cljx: 'clojure',
  clojure: 'clojure',
  coffee: 'coffee',
  iced: 'coffee',
  hbs: 'mustache',
  handlebars: 'mustache',
  hjs: 'mustache',
  rhtml: 'html_erb',
  j2: 'jinja',
  // misc languages
  hcl: 'terraform',
  tex: 'tex',
  ltx: 'tex',
  sty: 'tex',
  bbx: 'tex',
  cbx: 'tex',
  adown: 'argdown',
  argdn: 'argdown',
  // config / properties
  env: 'config',
  properties: 'config',
  cfg: 'config',
  conf: 'config',
  ini: 'config',
  ignore: 'git',
};

/**
 * Resolve a file path to a Seti icon asset URL, matching VS Code's Seti theme.
 *
 * @param {string} path
 * @returns {string}
 */
export function fileIcon(path) {
  const base = (path.split('/').pop() || '').toLowerCase();
  if (BY_FILENAME[base]) return ICONS[BY_FILENAME[base]] || ICONS.default;

  const parts = base.split('.');
  // VS Code matches the longest extension suffix first (`a.spec.ts` → `spec.ts`).
  for (let i = 1; i < parts.length; i++) {
    const name = BY_EXT[parts.slice(i).join('.')];
    if (name) return ICONS[name] || ICONS.default;
  }
  // Otherwise fall back to the file's language association (last extension).
  const langName = BY_LANG[parts.at(-1)];
  return (langName && ICONS[langName]) || ICONS.default;
}

/** Folder icon asset URL (open/closed share the same glyph here). */
export function folderIcon() {
  return ICONS.folder;
}
